// client/src/components/authentication/Form.jsx
import React, { useState } from 'react';

import { Button, Form, Message } from 'semantic-ui-react';

const AuthenticationForm = props => {
    const initialInputsState = {};
    for (const input in props.inputs) {
        initialInputsState[input] = {
            ...props.inputs[input],
            value: '',
            isValid: false,
            isTouched: false
        };
    }

    const [inputsState, setInputsState] = useState(initialInputsState);
    const [isFormValid, setIsFormValid] = useState(false);

    const changeInputHandler = (key, event) => {
        const inputValue = event.target.value;
        setInputsState(prevInputsState => {
            const newInputsState = {
                ...prevInputsState
            };
            for (const input in newInputsState) {
                newInputsState[input] = {
                    ...prevInputsState[input]
                };
            }
            newInputsState[key].value = inputValue;
            newInputsState[key].isValid = newInputsState[key].validate(
                newInputsState[key].value
            );
            newInputsState[key].isTouched = true;

            let newIsFormValid = true;
            Object.values(newInputsState).forEach(
                input => (newIsFormValid = newIsFormValid && input.isValid)
            );
            setIsFormValid(newIsFormValid);
            return newInputsState;
        });
    };

    const submitHandler = event => {
        const inputsValues = {};
        for (const input in inputsState) {
            inputsValues[input] = inputsState[input].value;
        }
        props.onSubmit(inputsValues, event);
    };

    return (
        <Form
            onSubmit={submitHandler}
            loading={props.isLoading}
            error={props.error !== null}
            noValidate
        >
            <Message
                error
                header="Authentication error"
                content={props.error}
            />
            {Object.entries(inputsState).map(([key, input]) => (
                <Form.Input
                    key={key}
                    onChange={event => changeInputHandler(key, event)}
                    iconPosition="left"
                    error={
                        input.isTouched &&
                        !input.isValid &&
                        input.validationError
                    }
                    icon={input.icon}
                    type={input.type}
                    placeholder={input.placeholder}
                />
            ))}
            <Button
                primary
                fluid
                content="Submit"
                disabled={!isFormValid}
                style={{ background: '#247291' }}
            />
        </Form>
    );
};

export default AuthenticationForm;

// client/src/components/auth/Form.svelte
<script>
    // TDOD check everything for validation + add button blocking on invalid form

    import Input from './Input.svelte';
    import ToggleSwitch from '../UI/ToggleSwitch.svelte';

    export let inputs;
    export let submit;
    export let buttonContent = 'login';

    let isFormValid = false;

    let isTeacher = false;

    const inputChangeHandler = (event, inputName) => {
        let isFormValidToNow = true;
        const input = inputs[inputName];
        const [isValid, errorMessage] = inputs[inputName].validate(event.target.value);
        inputs = {
            ...inputs,
            [inputName]: {
                ...input,
                value: event.target.value,
                isValid, errorMessage, isTouched: true
            }
        };
        Object.values(inputs).forEach(input => {
            isFormValid = isFormValid && input.isValid;
        });
    };

    const submitHandler = event => {
        event.preventDefault();
        let values = {isTeacher};
        for (let key in inputs) {
            values[key] = inputs[key].value;
        }
        submit(values);
    };
</script>

<form on:submit={submitHandler} novalidate>
    {#each Object.entries(inputs) as [key, input]}
        <Input
            value={input.value}
            type={input.type}
            placeholder={input.placeholder}
            isValid={input.isValid}
            isTouched={input.isTouched}
            errorMessage={input.errorMessage}
            background={input.background}
            on:input={event => inputChangeHandler(event, key)}
        />
    {/each}
    <ToggleSwitch on:change={event => isTeacher = event.target.checked} />
    <button type="submit">{buttonContent}</button>
</form>

<style>
    form {
        width: 80%;
        margin: 0 auto;
        padding: 0 .5rem 1rem;
    }

    button {
        width: 100%;
        height: 2rem;
        background: red;
        color: white;
        border: none;
        font: inherit;
    }

    button:focus {
        outline: none;
    }
</style>
