// client-react/src/components/Layout/index.jsx
import React, { useState } from 'react';

import LogIn from '../auth/LogIn';
import Modal from '../UI/Modal';
import SignUp from '../auth/SignUp';
import Toolbar from '../navigation/Toolbar';

import styles from './index.module.css';

const Layout = props => {
    const [shownForm, setShownForm] = useState(null);

    const showSignUp = () => setShownForm('Sign Up');
    const showLogIn = () => setShownForm('Log In');
    const showBecomeTeacher = () => setShownForm('Become teacher');
    const closeForm = () => setShownForm(null);

    const forms = {
        'Sign Up': <SignUp onClose={closeForm} />,
        'Log In': <LogIn onClose={closeForm} />,
        'Become teacher': <h1>Become teacher</h1>
    };

    return (
        <>
            <header className={styles.Header}>
                <Toolbar
                    showSignUp={showSignUp}
                    showLogIn={showLogIn}
                    showBecomeTeacher={showBecomeTeacher}
                />
            </header>
            <main>
                <>
                    <Modal isShown={shownForm} onClose={closeForm}>
                        {shownForm && forms[shownForm]}
                    </Modal>
                    {props.children}
                </>
            </main>
        </>
    );
};

export default Layout;

// client/src/routes/_layout.svelte
<script>
	import LogIn from '../components/auth/LogIn.svelte';
	import SignUp from '../components/auth/SignUp.svelte';
	import Toolbar from '../components/navigation/Toolbar.svelte';

	let shownAuth = null;
	const showLogIn = () => shownAuth = 'logIn';
	const showSignUp = () => shownAuth = 'signUp';
	const closeAuth = () => shownAuth = null;
</script>

<header>
	<Toolbar {showLogIn} {showSignUp} />
</header>

<main>
	{#if shownAuth === 'logIn'}
		<LogIn close={closeAuth} />
	{:else if shownAuth === 'signUp'}
		<SignUp close={closeAuth} />
	{/if}
	<slot></slot>
</main>

<style>
	header {
        border-bottom: 2px solid #aaa;
	}
</style>
